### ISSUE TITLE
feature suggestion: encrypt wuerfelware.txt

### ISSUE THREAD

**Issue by Hendonk** [heinrich-ulbricht/wuerfelware-passphrases-for-keepass#1]
thank you for creating the plugin, I just have one feature suggestion:

making the source file wuerfelware.txt unreadable would be helpful to make it less likely for attackers to know the word set we are working with to generate our passwords.

alternatively, giving the option to choose the source file immediately before password generation would make it possible to store it separately, in a place less conspicuous than the plugins folder of keepass; while also making it possible to work with different source files for different passwords.

**Comment by heinrich-ulbricht** [comment]
@Yemono Thanks for the suggestion. Secrecy of the word list is not supposed to be part of the pass phrase's security. It would be like keeping the alphabet secret you choose characters for a password from. But everybody is allowed to know that there are characters a-z, numbers 0-9 and so on. 

The word list is like an alphabet known to everybody. What's secret is which words you chose. Take 6 words randomly and - with a word list containing 10000 words - you have 10000^6=1000000000000000000000000 possible passphrases. Bruteforcing that making a trillion guesses per second ([Edward Snowdens assumption in 2015](https://theintercept.com/2015/03/26/passphrases-can-memorize-attackers-cant-guess/)) while _knowing the word list_ would take >31000 years. This should be ok.

I'm closing this suggestion as the title is about encrypting the word list. Feel free to open another feature suggestion for multiple word list support with some context of why would this be useful to you. I can see this being useful when using different languages, different word lengths etc.
