### ISSUE TITLE
Keepass 2.38 update

### ISSUE THREAD

**Issue by gjf** [heinrich-ulbricht/wuerfelware-passphrases-for-keepass#2]
New Keepass version (2.38) requires an update of this addon.

**Comment by heinrich-ulbricht** [comment]
The plugin seems to work fine with 2.38 without any changes.

**Comment by gjf** [comment]
It does not start at all asking about updating plugin for this version of KeePass.

**Comment by heinrich-ulbricht** [comment]
@gjf That's strange. I updated Keepass, started it and the plugins were working fine. Could you post a screenshot of the error message? And are you using the portable Keepass version or the installer?

**Comment by gjf** [comment]
I am using portable version that worked OK before update.
Screenshots are attached. I also attached other "problem" messages, although all other addons work OK.
![mswifiimport](https://user-images.githubusercontent.com/322186/35564079-03755ad2-05ca-11e8-9a79-fe1482fd0885.jpg)
![partialkeepassdatabaseexport](https://user-images.githubusercontent.com/322186/35564080-03b8945a-05ca-11e8-8db0-3b7ac1e88196.jpg)
![pwgenwuerfelware](https://user-images.githubusercontent.com/322186/35564081-03eadcd0-05ca-11e8-8f78-5bf2343ee31f.jpg)

**Comment by heinrich-ulbricht** [comment]
@gjf latest release 1.0.1 has been built against Keepass 2.38 - could you please check that this makes the error go away?

**Comment by gjf** [comment]
Where could I find it?
https://github.com/elgesl/keepass-mswifiimport/raw/master/MSWifiImportPlugin.dll - the error remains the same.

**Comment by heinrich-ulbricht** [comment]
@gjf You can find the latest release for the Würfelware plugin here: https://github.com/heinrich-ulbricht/wuerfelware-passphrases-for-keepass/releases/tag/v1.0.1
The MSWifiImportPlugin.dll is not under my control - you would have to open an issue with them.

**Comment by gjf** [comment]
Yeah, I posted the wrong URL, my mistake.
I can confirm your plugin works now. Thank you.
Are you going to do the same for partial-keepass-database-export?

**Comment by gjf** [comment]
By the way the situation appears again with update to 2.39.

**Comment by heinrich-ulbricht** [comment]
@gjf Still strange that it works on my machine (tm) - no rebuild necessary for newer KeePass versions. But here it is, I updated the release 1.0.1 for KeePass 2.39.
I will update the other plugin as well.
